# Generated by Django 4.1.6 on 2023-02-01 18:25

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('qr', sorl.thumbnail.fields.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
