# Generated by Django 4.1.6 on 2023-02-09 14:07

import app.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.CharField(default=app.models.custom_id, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=512)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, max_length=255, null=True, upload_to='qr-codes/logos/')),
                ('qr', sorl.thumbnail.fields.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='')),
                ('error_correct', models.SmallIntegerField(choices=[(1, 'Se pueden corregir alrededor del 7% o menos de los errores'), (0, 'Se pueden corregir alrededor del 15% o menos de los errores'), (3, 'Se pueden corregir alrededor del 25% o menos de los errores'), (2, 'Se pueden corregir alrededor del 30% o menos de los errores')], default=0)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
