# Generated by Django 4.1.6 on 2023-02-02 13:26

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AddField(
            model_name='url',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=255, null=True, upload_to='qr-codes/logos/'),
        ),
    ]
