# Generated by Django 4.1.6 on 2023-02-08 18:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_url_options_url_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default=app.models.custom_id, max_length=11, primary_key=True, serialize=False),
        ),
    ]
