# Generated by Django 4.1.6 on 2023-02-08 19:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='error_correct',
            field=models.SmallIntegerField(choices=[(1, 'Se pueden corregir alrededor del 7% o menos de los errores'), (0, 'Se pueden corregir alrededor del 15% o menos de los errores'), (3, 'Se pueden corregir alrededor del 25% o menos de los errores'), (2, 'Se pueden corregir alrededor del 30% o menos de los errores')], default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default=app.models.custom_id, editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
